version: '3'
services:
  web:
    build: .
    image: flask-example
    container_name: chunks-service
    command: gunicorn -c gunicorn.conf app:app
    network_mode: "host"
    sysctls:
      net.core.somaxconn: 10240